### ISSUE TITLE
Connection not becoming active

### ISSUE THREAD

**Issue by gempir** [gempir/go-twitch-irc#10]
The message

`:tmi.twitch.tv 001 justinfan123123 :Welcome, GLHF!` is somehow not evaluated correctly because Strings.HasPrefix doesn't work on the raw message. Strings.Contains works. Something with the PR #7 must have caused this.

https://github.com/gempir/go-twitch-irc/blob/master/client.go#L120

Pushing a quickfix with Strings.Contains for now

We should do some tests that actually connect to twitch, or need to improve our Mock

**Comment by gempir** [comment]
Any idea? @VitorFalcao

**Comment by VitorFalcao** [comment]
Well, the only thing I changed on the "readConnection" function was the parameter type to "*tls.Conn". I will run some tests here. How did you test it, please?

**Comment by gempir** [comment]
Just run the example in the Readme and you will see that it won't print any messages

**Comment by gempir** [comment]
I pushed a fix for now on the master though

**Comment by VitorFalcao** [comment]
I am having trouble finding a channel to join here "client.Join("gempir")". What channel did you join?

**Comment by gempir** [comment]
Doesn't matter just do gempir and type something into the chat over at twitch.tv/gempir

**Comment by gempir** [comment]
But twitch sends the 001 earlier than that. So you don't even need to join a channel to reproduce this

**Comment by VitorFalcao** [comment]
Ok. Just to make sure: with Strings.HasPrefix it does not become active, because it fails do parse the raw message, correct?

**Comment by gempir** [comment]
Well there is no parsing.

When I tested the new version earlier I noticed not being able to join channels, that was because the connection was never marked as active and that was because the if with strings.HasPrefix never went true

**Comment by VitorFalcao** [comment]
Well, as far as I know, Strings.HasPrefix shouldn't work really, because the message we get is: `[:tmi.twitch.tv 001 justinfan123123 :Welcome, GLHF!]` and we check if it starts with `:tmi.twitch.tv 001`, which is false. It should be `[:tmi.twitch.tv 001`

**Comment by VitorFalcao** [comment]
Ok, now it is working with HasPrefix, the connection becomes active. Now it's hanging here:
[https://github.com/gempir/go-twitch-irc/blob/master/client.go#L114](url)

**Comment by VitorFalcao** [comment]
@gempir It is actually working with `Strings.HasPrefix`. But it is not receiving any messages... Any idea? It receives and responds to the PING messages periodically, though.

**Comment by VitorFalcao** [comment]
@gempir I was debugging the code and I've found the following: `client.Join("gempir")` is called before `client.Connect()`. But it's `client.Connect()` which causes the connection to become active ```golang
if !c.connActive && strings.HasPrefix(msg, ":tmi.twitch.tv 001") {
    c.connActive = true
}
```

**Comment by gempir** [comment]
I think we need to use a go routine for Join. Not in the Client but somewhere inside it the lib.

Or we need to throw and error that the client isn't connected yet that's why he can't join channels.

We should adjust the Readme example accordingly.

Maybe we should look how other irc libs get around this problem?

**Comment by VitorFalcao** [comment]
> I think we need to use a go routine for Join. Not in the Client but somewhere inside it the lib.

I actually think we need to run this piece of code in a go routine:

```go
for {
    line, err := tp.ReadLine()
    if err != nil {
        return err
    }
    messages := strings.Split(line, "\r\n")
    fmt.Println(messages)
    for _, msg := range messages {
        if !c.connActive && strings.HasPrefix(msg, ":tmi.twitch.tv 001") {
	    c.connActive = true
        }
	c.handleLine(msg)
    }
}
```

Running `Join()` would solve only one problem. We still need to address the problem of sending messages. Or we could create 2 go routines, on for each (Join and sending messages). What do you think?

> Maybe we should look how other irc libs get around this problem?

That's a good idea. I will have a look at some.

**Comment by VitorFalcao** [comment]
I was looking at this repo: [https://github.com/Francesco149/shigebot](url) and found out this lib: [https://github.com/thoj/go-ircevent](url) It supports TLS. We could build something on top of it, what do you think? Or you rather build everything?

**Comment by gempir** [comment]
No not on top of it. I want to keep go-twitch-irc free of dependencies.

Just look how they solved problems

**Comment by VitorFalcao** [comment]
Ok. Will fix that then.

**Comment by VitorFalcao** [comment]
@gempir I have fixed the issue, but I would need to rewrite all the tests, in order for it to pass on Travis. Should I open a PR with the code I've written and then submit another PR for issue #8 ?

**Comment by gempir** [comment]
Do whatever is easier for you.

**Comment by VitorFalcao** [comment]
I will submit 2 PR's then. I think it will be more organized.

**Comment by VitorFalcao** [comment]
@gempir In the previous version (no SSL), did ir work correctly? Did it receive and send messages correctly? Were you able to see messages at https://go.twitch.tv/gempir?
