### ISSUE TITLE
initialJoins ignores message limits when reconnecting

### ISSUE THREAD

**Issue by IAmFletcher** [gempir/go-twitch-irc#102]
At the moment, we attempt to join all the channels in `client.channels` when we reconnect to Twitch. This means if a user has already joined 100+ channels, they will [exceed their limit](https://dev.twitch.tv/docs/irc/guide#command--message-limits) without knowing, unless they're a Verified Bot.

```go
func (c *Client) initialJoins() {
	// join or rejoin channels on connection
	c.channelsMtx.RLock()
	for channel := range c.channels {
		c.send(fmt.Sprintf("JOIN #%s", channel))
	}
	c.channelsMtx.RUnlock()
}
```

`OnReconnectMessage` should send the user the list of the channels they've already joined, and let them handle it. While this does break the API,  the user should be in control of any commands that count towards their message limit.

I'm currently playing around with a solution for #82 that will reduce calls by 20 and solve a majority of use-cases.

**Comment by gempir** [comment]
I disagree. I think it's our task to queue the reconnect messages so the user doesn't get hit by the rate limit.

**Comment by FletcherCodes** [comment]
I considered that, but we'd have to know the bot type (Normal, Mod, Known, or Verified) because of the difference in limits. And we'd have to let the user know the # of commands we're using, and for how long. Otherwise while we may not be exceeding the rate limit, the combination of our JOIN commands and theirs could push them over.

The first could be achieved with a new `BotType` value in the `Client` struct that is set to a default of Normal. Or we could have a more explicit value, such as `ReconnectCommandsPerMinute`.

If we add the `BotType` value, we should document the # of commands per minute we'll use on a reconnect. And then for both, we'll either have to provide the # of channels so they can calculate when they'll have the full rate limit back, or provide a a function that returns the time they'll have the full rate limit back.

**Comment by gempir** [comment]
> Otherwise while we may not be exceeding the rate limit, the combination of our JOIN commands and theirs could push them over.

What exactly do you mean with this. Every command through us should be ratelimited by ourselves to protect a user from twitch rate limits. We can get the BotType from IRC tags, we might need to send a message for that i'm not 100% sure. 

And in the code we just have the rate limits hardcoded for each bot type. This is my idea right now. 
I don't want to confuse the user with commands per minute etc. as a consumer of our client he shouldn't need to get that deep into TMI.

**Comment by FletcherCodes** [comment]
Oh, I didn't realise you wanted to handle the rate limit for everything. If that's the case then yeah, you can go ahead and ignore that part about the combination of our JOIN commands and theirs.

I think the only place you can get the BotType from is an API call. However, we easily send users to [Dakoda](https://dakoda.ga/lookup/). Then it's just a case of "Are you a mod in the chat?" and/or "Do you have one of these two options in Dakoda?".

**Comment by gempir** [comment]
Then we should start making API calls I guess. I mean as a start we can just make it configurable and give them a link to Dakoda but I think the goal should be to fetch that ourselves, we'll need API integration sooner or later anyway I would guess.

**Comment by RAnders00** [comment]
`JOIN` commands have no message limit, they don't count towards your 100-per-30 rate limit. Only thing you have to make sure is your receive buffer doesn't grow too fast with all the names/JOIN/ROOMSTATE messages you will receive.

**Comment by RAnders00** [comment]
Maybe rejoin should use c.Join() then, so it uses the existing logic to join quickly using `JOIN #a,#b,#c`

**Comment by IAmFletcher** [comment]
I thought they did count towards the command rate limit? If not, there is still a limit for how many channels you can join in a period of time. It's currently 50 joins/parts per 15 seconds, and 10 channels in one command still counts as 10 channels. [Source](https://discuss.dev.twitch.tv/t/the-final-answer-on-join-limits/8505/2)

**Comment by RAnders00** [comment]
That thread is from December 2016 and empirical evidence from today shows no limits are being enforced anymore. You can join hundreds of channels in seconds without being kicked from the server.

To test yourself:

```bash
cat <(echo -e 'CAP REQ :twitch.tv/commands twitch.tv/tags twitch.tv/membership\r\nNICK justinfan12345\r\nJOIN #00000000000000000000000ii,#0000000000000000000doter,#00_quanta,#0909090,#0despair0,#0hrigami,#0necrotix0,#0unknown000,#10000nams,#10007993,#104fred,#12106993,#123ghetto321,#123krappa,#1334567899,#1337sph,#13aldo,#13bordereagle,#17five151,#18biaobiao,#1992rum,#19manu90,#1bubuka,#1crazyrapotier,#1dahcookie1,#1ino_pommes,#1jasi,#1lordfred,#1marauder,#1sin,#1truong,#1ts_k1ng,#1upgamingbkk,#1wintime1,#1xoom,#2000voltz,#2009fan,#21century21,#21comawhite,#22franky22,#28maytragedy,#2direct,#2discombobulate,#2dwar,#2ez4bulldawg,#2ez4isaac,#2ez4symp,#2fear2,#2fusionn,#2h_turles,#2hard2explain,#2nyit,#2pkh,#2puckthefaeriethug,#2stepfromzero,#30ozyeti,#32149255,#322donger,#322usdollar,#32into2,#33kg,#3fces,#3fonoff,#3x0rt,#420bl4z3itkappa,#420choke,#420chop,#420plsgo420,#4headspammer_,#4kprince,#4lbedo,#50shadesofrtz,#5chelovektima,#5hahah,#5t_anger,#5wa7,#6138455,#624pt2,#68gachibass69,#69noir,#70457,#7851469,#786d,#7benboe,#7boeing,#7kplayer,#7purplebeans,#801phantom,#8030,#8bits239,#9304211,#999poketrainer,#9k8u7y6,#9kmmrbot,#9omi,#9tony6,#a29c_adam,#a4johnny,#a5pursuit,#a6pukoc22,#a_black_mail,#a_dogma,#a_lard_4_we,#a_rogue1,#aaejii,#aaer0x90,#aalvinreyes,#aaroc182,#aaronchan94,#aasher,#aashif,#aastrim,#aatomsk,#abadzxc01s,#abahala,#abduh90,#abdul_jarakul,#abekatinde,#abemuk,#aberracja,#abhorra,#aboredboard,#aboutblank77,#absohlutely,#acaesien,#accerous,#accisc,#acermon001,#acexg,#acgsteve,#acineo,#ackers20,#acoustic_1,#acowne63,#acvong,#adam_epsilon,#adamatoom,#adambunion,#adaminusblack,#adamu315,#addepladde,#addledexpire,#addonkis,#addyxstriker,#adekknakick,#adelyz02,#adib_70,#adiilaide,#adio09x,#admin_cardinal,#admiraigoldenretriever,#admiral_donger93,#admiralban,#admiralbullbot,#admiralbulldog,#admiralbullsh1t,#admiralcooldog,#admiraldito,#admiralgorgc,#admiralluldog,#admiredbulldog,#admquackbar,#adn_miz,#adonai_hm,#adrian080800,#adrianrm24,#adrianzihe,#adurpadurp,#ady6,#adzmak,#aeggy,#aegonva,#aeiotuiiaa,#aejfyfan,#aemillii,#aemineff,#aeon_af,#aero_legiongaming,#aesona_,#aetavicus,#afilthynormie,#aflymon,#afozasky,#afterzzz,#ag0ny3,#ageden14,#agengtriwahyudi,#agent_fighter,#aglarod,#agrail4ik,#agreydifferentcorner,#agungherzaman,#ahj000,#ahmadgeng,#ahnaf50,#ahnfkhr,#ahtuz,#aiazymeme,#aigroti,#aikhii,#ailithdesu,#aimeeoooo,#aintnotrihard,#aion511,#airrunkats,#aisaka_,#aishura_mao,#aiz___,#aizany123,#ajank128,#ajaxmont,#ajaxshree,#ajaxvonvos,#ajdg07,#ajiblegend,#ajiitv,#ajitirta,#ajusta_1505,#akarinhaai,#akatsuki_jj,#aken71,#akeng90,#akihabarawasteland,#akke017,#akkma,#akmalkgc,#akmlidrs,#akrit90,#akuarian,#akuma221,#akuma__,#akung36,#akveron_,#akylus_,#akzulu,#al_kupown,#alabaster_slim,#alabean15,#alabor_br,#aladdinn12,#aladdownthunder,#alain4k_,#albanczyk_,#albellus,#aldebaranst,#aldiiska,#alecbiff,#aleeeksz,#alejos13,#aleks9t,#aleksandarussr,#aleqthunder,#ales_,#alesao,#aleuts,#alevkun,#alex03902,#alex_893,#alex__thekid,#alexchann,#alexid4,#alexlixus,#alexmtz90,#alexthemoonguy,#alexx3228,#aley1aw,#alfonsswe,#alfredo2108,#alialastair,#aliboyw,#alicesaysrawr,#aliflalala,#alistical2,#aliza,#alkowy,#alkyythebest,#allangoes92,#allbreak3r,#allciti,#allday__,#allec23,#allenwtf,#alleuto,#alleyhsn,#allmanly,#allure_5,#almondvon,#alon__so,#alonepvp,#alpachinoo,#alpensoul,#alpha_virtue,#alphamommy,#alpinetwist,#alrescha_,#alrogue,#alsasfo,#alstjd2tp,#alston321,#altringer,#alucard511,#aluco,#alukar_,#alvabes,#alvarocu24,#alvelon,#alvianravi,#alvineey,#alzcats,#amadeusx23,#amaroxq,#amaskpt,#amazinghaihorn,#amazingzen,#ambrosadorjr,#americantp,#amieatsushi,#amimbitassu,#aminamin007,#amingeraie,#amir2393,#amirhosseintk007,#amirica90,#amirishere,#amirixsimous2,#amirjanshekar,#ammarhasnul,#amnedo,#amonhans,#amp3346,#an_maverick,#anaaaakin,#analphabeta,#analyse030,#anamazingman,#anangryman101,#ananzap,#anarchykappa,#anastasys,#anatomygiga,#ancientpriest_,#andiwebtv,#andormecha,#andranik,#andrewholty,#andrewwgan,#andreypb11,#andreythegreat,#androiam,#andy3000_,#andy_frosty1210,#andyngui,#anele_baba,#anelechan,#aneleclat,#angelloelperfecto,#angeloflight,#angelsack1,#anglesqt,#angrymarty777,#angryweasel_xlii,#aniiika,#animeisreall\r\n') - | nc irc.chat.twitch.tv 6667
```

Which is 363 channels joined in roughly 10 seconds, and no issues.

A while back I did extensive digging and research to figure out the details to this which i summed up in this document: https://hackmd.io/s/HyBXt_KrN (Which is saved under the !ratelimits command on pajbot)

**Comment by IAmFletcher** [comment]
Oh wait, you're the person behind the hackmd doc I was pointed towards. Yeah, I was going off of that and responses from people in the TwitchDev Discord regarding the JOIN/PART rate limit.

Well, thanks for that document, and for clearing it up. So the only rate limits at the moment are the PRIVMSG and WHISPER ones?

**Comment by RAnders00** [comment]
Exactly, as far as I know the described rate limits will apply + if your receive buffer gets too full you will be disconnected (I made an issue to remember to investigate that in detail and add a section about that)

**Comment by gempir** [comment]
This issue is very outdated and many things have changed. We also have a join ratelimter now, so this shouldn't be an issue anymore.
