### ISSUE TITLE
Support fast joining with multiple channels per JOIN command

### ISSUE THREAD

**Issue by RAnders00** [gempir/go-twitch-irc#106]
The IRC specification allows for this construct:

```
JOIN #a,#b
```

Up to the maximum message length of 512 bytes. On twitch, this limit is 4096 bytes, so a single command can easily join multiple hundreds of channels.
The response is the same as if you did `JOIN #a\r\nJOIN #b\r\n`, but a lot faster.

**Comment by gempir** [comment]
So this issue is just about increasing the limit?

**Comment by RAnders00** [comment]
Oh, i didn't know this was already supported. Can close then. Sorry
