### ISSUE TITLE
JOIN not used

### ISSUE THREAD

**Issue by Shagrat2** [gempir/go-twitch-irc#117]
If you do Disconnect and then Connect. JOIN doesn't work even manually

Make it possible to clean the cache of connected channels

**Comment by gempir** [comment]
Thanks for the bug report.

**Comment by pajlada** [comment]
@Shagrat2 Can you verify that this happens for you on version v2.2.2?

**Comment by Shagrat2** [comment]
Thank you began to work.
Although I did exit and enter at every discount / conect
