### ISSUE TITLE
Can I use it without login?

### ISSUE THREAD

**Issue by yms2772** [gempir/go-twitch-irc#123]
TMI of node.js can fetch a chat without login, but is it not here?

**Comment by gempir** [comment]
Use the client out of the example 

```twitch.NewClient("justinfan123123", "oauth:123123123")```

TMI has a secret anonymous user that is called justinfanXXX and you can numbers like you want behind it. Oauth doesn't matter either.

**Comment by gempir** [comment]
I'll reopen this, maybe we could add a constructor for it. 

`twitch.NewAnonymousClient()`

**Comment by pajlada** [comment]
`twitch.NewAnonymousClient()` has now been implemented and will be part of the next release. Thanks for making the issue!
