### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by gempir** [gempir/go-twitch-irc#128]
This is a list of breaking changes we might want to introduce in v3

- [x] remove membership from default capabilties context #126  #174

**Comment by deefdragon** [comment]
@gempir having a hard time determining based on the discussion in #102 , is the rate limiting already in place, or something that you want to see added in V3? I don't see any sign of limiting when I briefly looked through the code, but I may have missed something.

**Comment by gempir** [comment]
@deefdragon There is currently no rate limiting in place. Neither for sending messages or joining channels or anything else. 

Would certainly be a good feature for V3, I have also played around in with just scaling connections, which is more useful than limiting IMO. https://github.com/gempir/go-twitch-irc/pull/144

Put I can't really find the time and energy to actually implement it in a good and clean way. That PR was just some rough ideas.

**Comment by deefdragon** [comment]
I'm sure scaling connections would be useful, but as far as the documentation lists, limits are [per user.](https://dev.twitch.tv/docs/irc/guide#command--message-limits) I suspect many bots could easily break those rate limits if not careful after a reboot. If what I make to mitigate that for myself is reasonable and clean, I will see if I can migrate it in. I feel like, even if some are not implemented anymore as was hinted at in 102, some respect should still be given to the documented rate limits.

Thanks for the clarification.

**Comment by gempir** [comment]
Yeah for sure. The Ratelimits should be respected anyway and be adjustable aswell. The Scaling is just a possible future feature.
