### ISSUE TITLE
Does this handle ALL twitch IRC message types?

### ISSUE THREAD

**Issue by jung-kim** [gempir/go-twitch-irc#131]
First of all, thanks for the app!  it made my fun project more funner with golang!

Basically the question is that is this feature complete in a sense that all below message types are supported?  

I know channel subscription events are captured when listening to the `OnUserNoticeMessage()`.  But I was wondering about some of the rarer ones.  Like cheers, anonymous gifts, band, resubs and others.

Thanks!

**Comment by gempir** [comment]
Almost all message types besides 1 are supported (#98)
https://dev.twitch.tv/docs/irc/tags#overview

I am not 100% sure anymore which kind of events come through IRC, but not all of them do anymore. You need to use PubSub for some of it and some of it is straight up not available yet like channel points I think.
