### ISSUE TITLE
Add functions for chat commands

### ISSUE THREAD

**Issue by yms2772** [gempir/go-twitch-irc#137]
There is a function like below.
![image](https://user-images.githubusercontent.com/6222645/84667558-7cde8a80-af5d-11ea-8530-54953c08f4b5.png)

Is it possible to using that function with this package?

**Comment by gempir** [comment]
You can send chat commands easily like this:

`client.Say("gempir", "/followersoff")` or `client.Say("gempir", ".followersoff")`
 
It could be a bit easier so I'll keep this issue open so we might add functions for this later.

**Comment by yms2772** [comment]
@gempir Thank you!

**Comment by cocap10** [comment]
Hey @gempir
I would like to work on this issue :)
Can I pick it up ?
I just open this project. Do you have any tips to help me ?
Cheers

**Comment by gempir** [comment]
@cocap10 Yes. 

It would make sense to read this documentation https://help.twitch.tv/s/article/chat-commands?language=en_US and add commands that make sense on bots like followers mode. 

You can just add function to client.go which will call Say() internally and send the command that way.

**Comment by cocap10** [comment]
Thanks, I'm on it 👍

**Comment by gempir** [comment]
Closing this for now, FollowersOn and FollowersOff are functions now. Anyone is welcome to add more
