### ISSUE TITLE
handleNamesMessage: assignment to entry in nil map

### ISSUE THREAD

**Issue by bamnet** [gempir/go-twitch-irc#142]
Very infrequently, my client crashes with an error bubbling up from `handleNamesMessage`.  it looks like there is some race conditions when the connection map isn't setup correctly and tries to assign to `nil` instead of a map.

github.com/gempir/go-twitch-irc/v2.(*Client).handleNamesMessage(0xc000482780, 0xc00069afc0, 0x1b8, 0xa, 0xc00069afe0, 0x3, 0xc00069aff8, 0x9, 0xc000e50280, 0x25, ...)
external/com_github_gempir_go_twitch_irc_v2/client.go:1081 +0x111github.com/gempir/go-twitch-irc/v2.(*Client).handleLine(0xc000482780, 0xc00069afc0, 0x1b8, 0x0, 0x1)
external/com_github_gempir_go_twitch_irc_v2/client.go:1006 +0x294
github.com/gempir/go-twitch-irc/v2.(*Client).startParser(0xc000482780, 0xc01e78, 0xc000482780)	external/com_github_gempir_go_twitch_irc_v2/client.go:874 +0x112
github.com/gempir/go-twitch-irc/v2.(*Client).makeConnection(0xc000482780, 0xc000147dc8, 0xc00008b380, 0xcc9901, 0xc00020dd30)
external/com_github_gempir_go_twitch_irc_v2/client.go:727 +0x228
github.com/gempir/go-twitch-irc/v2.(*Client).Connect(0xc000482780, 0xe, 0x0)	external/com_github_gempir_go_twitch_irc_v2/client.go:677

**Comment by gempir** [comment]
Thanks for the bug report, this was now fixed in #143 and released with v2.4.2
