### ISSUE TITLE
Disconnect Function example not working.

### ISSUE THREAD

**Issue by Epiclemonaid** [gempir/go-twitch-irc#145]
I'm trying to have my website join and disconnect the bot but I've tried a few variations of a disconnect function and nothing is working. any help would be greatly appreciated.  I slimmed this down to the bare minimum for readability. is there anyway to have a disconnect function separate? I'm having trouble understanding the *client stuff. thanks in advance. 
```go
func joinSpecialbot(res http.ResponseWriter, req *http.Request) {
	rnd.HTML(res, http.StatusOK, "index", nil)
	check := "false"
	if check == "false" {
		addStreamerdb(channel_name, channel_id)
		client := twitch2.NewClient("xxxxxxxxxxxxxxxx", "xxxxxxxxxxxx",)
		client.OnPrivateMessage(func(message twitch2.PrivateMessage) {
			fmt.Println(message.Message)
			fmt.Println(message.User.Name)
			fmt.Println(message.Channel)
			replyChannel := message.Channel
			reply := message.User.Name
			command1 := message.Message
			if command1 == "!u" {
				client.Say("channel_name", "up @"+reply)
			} else if command1 == "!d" {
				client.Say(replyChannel, "down @"+reply)
			} else {
		})
		client.Join(channel_name)
		fmt.Println("joined channel")
		err := client.Connect()
		if err != nil {
			panic(err)
		}
	} else {
		fmt.Println("botalreadyjoined")
	}
}
```

**Comment by gempir** [comment]
What exactly are you talking about? You are not even calling client.Disconnect()

**Comment by Epiclemonaid** [comment]
sorry If that didnt make any sense. I was wondering if there was a way to disconnect the connection I made here with a separate disconnect function with a res, req so i could tie it to a `leave channel` button with my js frontend. any attempt ive made it doesnt disconnect since it doesnt see that connection. the bot is running at stream-tools.xyz its called banbot. I read the docs on the disconnect method but i dont know how to call it separately.

**Comment by Epiclemonaid** [comment]
I'm new to working with IRC bots in general. so this might be a noob question.

**Comment by Epiclemonaid** [comment]
this is the only functioning disconnect i've got working but i want to separate them. sorry again for the confusion. 
```go
func cronBanUsers(channel string) {
	client := twitch2.NewClient("xxxxxxxxxx", "xxxxxxx",)
	banlist := dailyBanbot()
	for _, ban := range banlist {
		client.Say(channel, "/ban @"+ban.Channel_name)
		//fmt.Println("Value: ", ban)
	}
	//client.Say("itslmnd", "userbanned")
	client.Join(channel)
	err := client.Connect()
	if err != nil {
		panic(err2)
	}
	err2 := client.Disconnect()
	if err2 != nil {
		panic(err2)
	}
}```

**Comment by Epiclemonaid** [comment]
thanks! that clears it up
