### ISSUE TITLE
Trim leading msg-param string from message parameters

### ISSUE THREAD

**Issue by hex-agon** [gempir/go-twitch-irc#147]
Hello, first of all i don't have much experience with this library but I'd like to make a suggestion.

My suggestion is to trim the leading `msg-param-` string from tags that are placed into the `userNoticeMessage.MsgParams` map. When i first saw this map my gut feeling was that it was a convenient way to access msg-params with a shorter key instead of the full key, which is not the case as the tags are just copied over as-is. This leads me to think there's not much use for the `MsgParams` as the same information is available on the `Tags` map. Did I misunderstood it's use or is this something that would be interesting to implement?

Things that would have to be done:
* Trim the  leading `msg-param-` string from tags placed into the `userNoticeMessage.MsgParams`
* Update the test cases accordingly

Concerns:
* This change would not be backwards compatible

**Comment by gempir** [comment]
I see the confusion. But the docs reference them always with the `msg-param-` prefix. I don't the giant value in having them in a map without the prefix for the huge cost of breaking backwards compatibility.

It would be nice to have it be a struct, with each field having correct types, but it having optional fields makes that kinda hard. Not sure what the idiomatic go solution would be to that.

**Comment by hex-agon** [comment]
I thought that the backwards incompatibility change would be a bit too much to bite, maybe something for another major version. Sadly I can't think of any other suggestion currently of how this could be implemented so I guess I'll just close this issue.

**Comment by gempir** [comment]
We have the V3 issue #128 to collect those kind of changes, but I personally don't even want the change. Like I said the keys are defined that way in the docs.
