### ISSUE TITLE
Whisper does not work

### ISSUE THREAD

**Issue by TroyDota** [gempir/go-twitch-irc#155]
```go
text := "Yes Sir!"

// Works
client.Say(message.Channel, fmt.Sprintf("/w %s %s", message.User.Name, text))
// Does not work
twitch.Whisper(message.User.Name, outMsg)
```

perhaps an implementation issue or some wrong values at
```go 
c.send(fmt.Sprintf("PRIVMSG #%s :/w %s %s", c.ircUser, username, text))
```
particularly `c.ircUser`

**Comment by TroyDota** [comment]
yiekes

**Comment by gempir** [comment]
Learning: 

The bot channel name needs to be correct in the client setup, otherwise it can't send whispers like that because it uses the bots own channel to send them.

**Comment by AndrewOrr** [comment]
What do you mean by correct? Say seems to work fine but whisper doesn't seem to be working.

**Comment by medcelerate** [comment]
@gempir Could you elaborate on this. I am using the latest version of the API and I am unable to send whispers even to the bot username itself.
