### ISSUE TITLE
Add support for for Reply message in PrivateMessage

### ISSUE THREAD

**Issue by higatowa** [gempir/go-twitch-irc#158]
Per specification, PrivateMessage also contains the info on the message that was replied.  

We can do something like that do add support to it 

in `message.go`

```
reply := Reply{
		ParentMessageID:   message.Tags["reply-parent-msg-id"],
		ParentUserID:      message.Tags["reply-parent-user-id"],
		ParentDisplayName: message.Tags["reply-parent-display-name"],
		ParentMsgBody:     message.Tags["reply-parent-msg-body"],
	}
	privateMessage := PrivateMessage{
		User: parseUser(message),

		Raw:     message.Raw,
		Type:    parseMessageType(message.Command),
		RawType: message.Command,
		Tags:    message.Tags,
		RoomID:  message.Tags["room-id"],
		ID:      message.Tags["id"],
		Time:    parseTime(message.Tags["tmi-sent-ts"]),
		Reply:   &reply,
	}
```

in `client.go`

```
type PrivateMessage struct {
	User User

	Raw     string
	Type    MessageType
	RawType string
	Tags    map[string]string
	Message string
	Channel string
	RoomID  string
	ID      string
	Time    time.Time
	Emotes  []*Emote
	Bits    int
	Action  bool
	Reply   *Reply
}

type Reply struct {
	ParentMessageID   string
	ParentUserID      string
	ParentDisplayName string
	ParentMsgBody     string
}

```

let me know what you think, I will be away for some weeks but can send a PR later

**Comment by gempir** [comment]
Yeah that would be a great addition! Code examples look solid as well.

**Comment by higatowa** [comment]
Nice when I can I will send a PR. but I have another question, why `Badges` in` Message.User` is `map[string]int` when it can be `map[string]bool`? Isn't just something like `key="moderator" value=1` etc?

**Comment by pajlada** [comment]
> Nice when I can I will send a PR. but I have another question, why `Badges` in` Message.User` is `map[string]int` when it can be `map[string]bool`? Isn't just something like `key="moderator" value=1` etc?

Sub badges contain int data for how many months they've been subbed or which sub badge to use (can't remember which one)

**Comment by gempir** [comment]
Released in https://github.com/gempir/go-twitch-irc/releases/tag/v3.1.0
