### ISSUE TITLE
Login authentication failed

### ISSUE THREAD

**Issue by 454406** [gempir/go-twitch-irc#166]
Hi,
My bot worked perfectly fine until yesterday (8 October 2021).
![image](https://user-images.githubusercontent.com/62300856/136665690-368381cf-3d1b-4e8b-a6b7-fb3a1c0b6eac.png)
"Login authentication failed"
I checked and resetted the stream key, which normally worked and replaced it with an oauth token and resetted that (variable: Token).
I added, checked and removed the channel id (variable: ClientId).
I toggled api.Settings.SkipAutoServerTokenGeneration.
And I added, checked and removed the secret (variable: Secret).
All resulted in the same error.
I tried the good old 'restart' too, but it didn't magically fix itself.

**Comment by gempir** [comment]
Did you change the password of your bot account? Then You need to re-generate a token

**Comment by 454406** [comment]
I didn't.

**Comment by gempir** [comment]
Also you are in the wrong repo. This isn't a C# twitch irc client. It's a go irc client.

**Comment by gempir** [comment]
Each time you go to the website and click Connect there it will generate a new token.
