### ISSUE TITLE
Extension Messages

### ISSUE THREAD

**Issue by DaniDipp** [gempir/go-twitch-irc#167]
Hi, are messages from extensions not supported?
They look similar to normal user messages on the website but aren't caught by `OnPrivateMessage`.

![2021-11-03T04-31-38](https://user-images.githubusercontent.com/17002453/140006595-ad6f4d8c-1e06-4812-bfc6-90663559e95d.gif)

**Comment by gempir** [comment]
I have never seen one of those in my life. But I think they are very likely just available via pubsub, and this library does not intend to support pubsub.

**Comment by DaniDipp** [comment]
Damn, thanks for the quick reply!
