### ISSUE TITLE
Userlist returns only one user (self)

### ISSUE THREAD

**Issue by ovelir** [gempir/go-twitch-irc#180]
Func UserList returns only one user from channel (the user on whose behalf the connection was made).
As far as I remember, half year ago or about it, function returned the full list of channel users.
Does the user need moderator rights or other conditions for correct work?

**Comment by pajlada** [comment]
> Func UserList returns only one user from channel (the user on whose behalf the connection was made). As far as I remember, half year ago or about it, function returned the full list of channel users. Does the user need moderator rights or other conditions for correct work?

Have you set the `Capabilities` field in the client to include the `MembershipCapability`?
so before connecting:
```go
	client.Capabilities = append(client.Capabilities, twitch.MembershipCapability)
```

**Comment by ovelir** [comment]
It works! Thank you :)

**Comment by yuriygr** [comment]
@gempir Maybe we should add this to the bot readme?

**Comment by gempir** [comment]
As far as I remember is user list defunct now. The capability is practically useless. You need to use helix for that.
