### ISSUE TITLE
Stop client.Connect() loop

### ISSUE THREAD

**Issue by windmeup** [gempir/go-twitch-irc#181]
When client.Disconnect() throw ErrConnectionIsNotOpen, there is no other way to break client.Connect() loop. Add a method to do this mybe convenient.

**Comment by pajlada** [comment]
Ah yeah, I can see that locking you into that connection loop.

I think this could be solved by making the client Context aware in the library and handling manual disconnects through that.

**Comment by windmeup** [comment]
For now, if want to disconnect, have to wait the connection active. Consider the reconnect loop exists, it's little more complicated. I think add something like dispose, may be convenient when some one want to shutdown the chatbot application at any time.
