### ISSUE TITLE
Read channel messages?

### ISSUE THREAD

**Issue by vikpe** [gempir/go-twitch-irc#185]
Is is possible to read channel messages? 

I'm writing a chat bot and want to respond to custom commands.

**Comment by pajlada** [comment]
The example in the readme shows how you can handle "private messages", that's messages that are received in a channel
https://github.com/gempir/go-twitch-irc#getting-started
Then it's up to you to handle the incoming message and respond with `client.Say` or any of the other available functions.
See https://pkg.go.dev/github.com/gempir/go-twitch-irc/v3 for other documented functions.
