### ISSUE TITLE
Bot stoping listening chat messages after while

### ISSUE THREAD

**Issue by Satont** [gempir/go-twitch-irc#189]
Hi, my bot stops listening events after some hours and i'm not sure why because library not logging any debug information.

Is there way to find out why it may happening and what i'm actually can do? As i see from code it should auto reconnect and join channels, right? Anyways i joining channel in `OnConnect` handler, so i'm expect long running instance. But currently i have to restart bot each ~10 hours.

**Comment by pajlada** [comment]
Are you logging your errors from the `Connect()` call? That might provide some details if it happens in combination with disconnects/reconnects

The way I handle this in my bot is with a loop that calls the `Connect()` function and behaves differently based on the error returned, and join channels before calling Connect

```go
bot.Join(channel)

for {
    accessToken := GetAccessTokenForBotAccount()
    bot.SetIRCToken("oauth:" + accessToken)
    err := bot.Connect()
    if err == twitch.ErrLoginAuthenticationFailed {
        ...
    }
```

the `Join` call can take place before the bot connects, and the library will automatically rejoin the channel whenever it connects/reconnects so there's no need for an `OnConnect` handler

**Comment by Satont** [comment]
No, totally forgot about that. I'll cover that case in my app.

Thank you. Probably it must be in readme so maybe someone will find useful that.
