### ISSUE TITLE
Test if connection is still alive or reconnect after client lost the network connectivity

### ISSUE THREAD

**Issue by PatrickFD** [gempir/go-twitch-irc#19]
First of all, thank you for your great work!

How can I test if my connection is still alive or reconnect after my client lost the network connectivity.

If the network connection gets interrupted the client still thinks that the connection is alive. I used the readme example, connected to my channel and turned off the network interface the client was listening on.

Before the interruption I sent some test messages and the client printed them on screen as expected but not after the reconnection.

What's the best way to handle such a situation?

According to the twitch docs [1] their servers send a PING every five minutes. Maybe we can check all x minutes what the difference between the last PING and the current time is, but that seems a bit sloppy.

[1]https://dev.twitch.tv/docs/irc#connecting-to-twitch-irc

best regards pfd

**Comment by gempir** [comment]
I know what you mean and I'm thinking about possible solutions. I have had my bot run for 10 days and then go silent for whatever reason, there is no error. 

This https://github.com/gempir/go-twitch-irc/blob/master/client.go#L127 doesn't throw an error so we gotta look elsewhere. no error here either https://github.com/gempir/go-twitch-irc/blob/master/client.go#L139

go-twitch-irc should definetly check for the PING and if it didn't happen reconnect. But beyond that it should detect if a network interface is disabled or something else happens. Not sure how yet.

I'll think about it.

**Comment by PatrickFD** [comment]
The problem is that the connection could be dead for a long time without a way of noticing. The client is still able to send data but won't receive an error.


>go-twitch-irc should definetly check for the PING and if it didn't happen reconnect.

There should be two ways to handle the connection. The first one is your recommendation to reconnect and the other one is to throw an NoHeartbeat error so that the developer can decide what to do.


>But beyond that it should detect if a network interface is disabled or something else happens. Not sure how yet.

I don't think that the lib should detect if the interface is up or not, because the issue is that the problem can be anywhere on the client <-> server route. Like the lokal network is up, but there is no internet connection or there is a problem with the twitch-irc servers and the TCP connection was not properly closed.

**Comment by gempir** [comment]
I wanna create a simple and robust client. No user of the library should think about reconnecting that should be handled all in the library.

And we can definitely do that with the pings. Not sure if it's possible faster on reaction of a connection loss.

**Comment by PatrickFD** [comment]
Ok, I understand that with a simple and robust client. The "only heartbeat error" was meant as an addition if devs want to handle it differently.

I will also have a look on how to check if the connection is still active, closed or dead, but unfortunately currently I have not that much time.

**Comment by gempir** [comment]
Ok.

What I found after my research is that net.TCPConn supports TCPKeepAlive (https://golang.org/pkg/net/#TCPConn.SetKeepAlive) sadly we use tls.Conn and this does not support TCPKeepAlive as it supports more than one protocol.

The idomatic way would be just using PING and PONG. Not sure how to implement it yet though.

**Comment by shawnbutts** [comment]
could you make use of tls.DialWithDialer?  If I read https://golang.org/pkg/crypto/tls/#DialWithDialer correctly, you can use net.TCPConn with all it's option first and then TLS connect is setup on top of that.

**Comment by gempir** [comment]
@shawnbutts not sure. 

If pass use net.DialTCP I still don't get the TCPConn anywhere I just get a resulting tls.Conn so where would I set the options?

**Comment by shawnbutts** [comment]
I think you set the timeout on the net.dialer.  i.e. https://github.com/gocql/gocql/blob/master/conn.go#L166

**Comment by gempir** [comment]
@shawnbutts Okay yeah but that timeout is not the same as TCPKeepAlive. The timout i can easily set in tls aswell I think

**Comment by shawnbutts** [comment]
sorry, the timeout was just an example.  you should have access to the full set of dialer options.  https://golang.org/src/net/dial.go

**Comment by gempir** [comment]
Alright I have created a PR #21 gonna test a bit and will merge if it runs good.

**Comment by gempir** [comment]
So this didn't help much. I'm still having the issue that after a few days the connection can die and you can't tell from the client. 

The ping method is required I guess.
