### ISSUE TITLE
Question: WakeUp message

### ISSUE THREAD

**Issue by CosasDePuma** [gempir/go-twitch-irc#23]
My issue is simple.
I want to send a message that says "Connected" when my bot is turned on and that it receives messages once it is turned on.

Any help? Thanx ^^

**Comment by gempir** [comment]
I'd say easiest currently would be listening on OnNewRoomstateMessage and wait that first roomstate message.

**Comment by CosasDePuma** [comment]
A listenner in a new roomstate message was my preferred option. I hoped there was a faster alternative.

Since this is not really an issue, you can close this thread.

Thank you :)
