### ISSUE TITLE
Silently dropping connection

### ISSUE THREAD

**Issue by jrbury** [gempir/go-twitch-irc#34]
I'm also currently having an issue where the connection gets silently dropped after an extended period of time running. 

I saw that https://github.com/gempir/go-twitch-irc/pull/25 was reverted. Was it not successful? What about it didn't work? I would be happy to take a crack at this, I just want to make sure I understand what's been done and why it didn't work.

I've started by taking a look at the discussion on https://github.com/gempir/go-twitch-irc/issues/19 but was wondering if you had anymore thoughts/insights.

**Comment by gempir** [comment]
Yeah. #25 wasn't sucessful, I'm not sure i haven't investigated more. But I think we still need a solution like it. Connection drops for me aswell after a very extended time period (like 5+ days). If you wanna give it a crack go ahead. That would be great.

**Comment by Sil1g** [comment]
It can be triggered by turning on/off VPN on my dev machine.
Sorry but I have no free time to do a further research right now

**Comment by jrbury** [comment]
@Sil1g Thanks, that gives me a good place to focus, that sounds like the underlying connection is dying/timing out/being killed and it's just not being caught.

**Comment by jrbury** [comment]
So I believeI have figured out what the issue is, when the connection dies (for any reason) we ARE successfully reconnecting. The issue is that we don't join any channels when we reconnect; this is because `client.Join` is just an alias for a pre-formatted message send and so we send the join message once (on our first connection) but not any subsequent successful connections.

A very simple fix for this could be to change the `client.Join` function so that instead of it being a message send, it instead updates a list of channels that should be joined, and then the join message is actually sent in the `setupConnection` function, this would mean the join commands are sent anytime we connect or reconnect.

**Comment by gempir** [comment]
Okay interesting. And we don't deal with Reconnect yet in any way.

**Comment by gempir** [comment]
Okay. Honestly unsure how we should handle this or if we even should. The issue with rejoining channels definetly needs to be adressed. There is no way in IRC of "restoring" a previous connection so we will have to rejoin the channels on a new connection.

**Comment by pajlada** [comment]
Fixed by @jrbury in #36 / #37 
Reopen if it turns out to not be fully fixed, or make a new issue
