### ISSUE TITLE
Total Bits from message

### ISSUE THREAD

**Issue by deef0000dragon1** [gempir/go-twitch-irc#35]
I may just be missing something, but I am wondering if there is a way to get the total bits from the message, or if that can be added somewhere. If I remember correctly, twitch includes the total somewhere in the raw message, but I don't remember for sure. 

I would just parse the message for cheer100 and what not, but it is possible to send "cheer100" from an IRC interface and have it not give bits.

**Comment by pajlada** [comment]
You can read out the total bits from a message by checking the `bits` tags in a PRIVMSG
An example of a bits message is
`@badges=staff/1,bits/1000;bits=100;color=;display-name=dallas;emotes=;id=b34ccfc7-4977-403a-8a94-33c6bac34fb8;mod=0;room-id=1337;subscriber=0;tmi-sent-ts=1507246572675;turbo=1;user-id=1337;user-type=staff :ronni!ronni@ronni.tmi.twitch.tv PRIVMSG #dallas :cheer100`

Without actually trying to compile the code, I think you could do this:
```go
client.OnNewMessage(func(channel string, user twitch.User, message twitch.Message) {
	if numBitsStr, ok := message.Tags["bits"]; ok {
		fmt.Println("User", user.Username, "cheered", numBitsStr, "bits!")
	}
})
`

**Comment by deef0000dragon1** [comment]
After running through my test data from last night I finally found the tags. I don't know how, but I did just miss it in my original testing. Thanks for the help. And the sanity check.
