### ISSUE TITLE
client.Say Not Outputting to chat and causing callbacks to not work

### ISSUE THREAD

**Issue by deef0000dragon1** [gempir/go-twitch-irc#41]
Was trying to get echoing working for my project. Bot wasn't talking. Ran a sanity check to try to see what it was. From what I can tell, client.Say is lagging something a lot. Running WITH the .Say eventually gets to the print "Done Saying", but still doesent print to the console anymore, OR speak in chat. Without the .Say, the connection is perfect and working as expected. 

 I validated the OAuth (generated here: https://twitchapps.com/tmi/ ) is able to chat by logging in through an IRC. This is my main account that I am also watching for chat through, but as far as I can tell, that shouldn't effect anything. 

```
	User := "deef0000dragon1"
	client := twitch.NewClient(User, "oauth:validoauth")

	client.OnNewMessage(func(channel string, user twitch.User, message twitch.Message) {
		fmt.Println(message.Text + " from " + client.IrcAddress)
	})

	client.Join(User)
	client.Say(User, "Bot Say Hi")
	fmt.Printf("Done Saying")

	err := client.Connect()
	if err != nil {
		panic(err)
	}
```

Am I missing something, or is it just not working?

**Comment by jrbury** [comment]
`client.Say()` blocks when the connection is not active, eventually giving up if it has to wait too long. You need to call `client.Connect()` _before_ calling `client.Say()`

**Comment by deef0000dragon1** [comment]
I should have checked that. Thank you. Was thinking that client.Join was the only thing required.
