### ISSUE TITLE
.connect crash silently

### ISSUE THREAD

**Issue by jscoys** [gempir/go-twitch-irc#46]
Hello,

Don’t know why but the program always stop executing à fêter .connect() one. Sometimes the chat ISMM connected sometimes not... I don’t receive any errors it’s weird could you help me please?

**Comment by gempir** [comment]
This isn't much to go on, what exactly happens and what does your code look like?

**Comment by gempir** [comment]
Without any further information, I'm going to have to close this issue. If you can give me more to go on feel free to write here again.
