### ISSUE TITLE
Clean up message parsing

### ISSUE THREAD

**Issue by gempir** [gempir/go-twitch-irc#5]
message parsing in message.go is pretty chaotic and still doesn't full represent all tags from Twitch

- less global functions
- more idomatic code
- improve Message and User structs to get closer to the definition by twitch (https://dev.twitch.tv/docs/v5/guides/irc)

**Comment by gmemstr** [comment]
Going to take a look at this, have to dive into those Twitch docs quickly.

**Comment by gempir** [comment]
@gmemstr are you still working on this?

**Comment by gmemstr** [comment]
Unfortunately not, have been sidetracked with other projects

**Comment by Tinee** [comment]
I give this a try.

**Comment by FletcherCodes** [comment]
Gonna give this a shot, but just wanted to check whether it's cool for me to make some breaking API changes. If not, and I'm going about this in the completely wrong way, I apologise. This is my first larger contribution to an OS library, and I'd appreciate any further guidance with regards to what you're looking for.

# Current Proposed Changes

1) Replace MessageType with the string we get from Twitch. At the moment, any types not added in 3 different places (enum declaration, `parseMessageType`, and `handleLine`) are sent as `UNSET` with a raw string.

By changing it to a string we can, at the bare minimum, give the user the message type, message text, and a map of tags. 

2) Change the Message struct, and possibly split it into two. One for common variables, and another for PRIVMSG that would embed the previous one. If you want, I could also create structs for the other message types too, when relevant.

---

Thanks again for making this library! I have no idea where to start with IRC stuff, especially when it comes to Go. 👍

**Comment by gempir** [comment]
1. I disagree with the approach of removing the MessageType, it should stay available as an enum, it's a kind of documentation. I could see that we just offer a field named rawMessageType or so incase we don't support it yet. 

2. That is heavily API breaking which I'm not a fan of. I don't see the massive benefits either. I would have to see the proposed structs first to decide if we should actually go through with these changes.

**Comment by FletcherCodes** [comment]
1. 👍
2. I've outlined the proposed structs for both options. I initially proposed this in response to:
>     * improve Message and User structs to get closer to the definition by twitch

# Option 1: Simple Split

I realised while figuring out the specifics of the structs that there is very few message types that don't utilise the extra data in `Message`. However, there is a couple that actually send a completely empty `User` struct.

This does break the API, but significantly less than the second option. However, it also hides the specifics of each message type in `Tags`.

```go
type RawMessage struct {
	Type    MessageType
	RawType string
	Raw     string
	Tags    map[string]string
}

type Message struct {
	RawMessage
	Time   time.Time
	ID     string
	RoomID string
	Emotes []*Emote
	Text   string
}

func OnNewUnsetMessage(callback func(channel string, user User, message RawMessage)) {}
func OnNewClearchatMessage(callback func(channel string, user User, message Message)) {}
func OnNewMessage(callback func(channel string, user User, message Message)) {}
func OnNewWhisper(callback func(user User, message Message)) {}
func OnNewRoomstateMessage(callback func(channel string, message Message)) {}
func OnNewNoticeMessage(callback func(channel string, message Message)) {}
func OnNewUserstateMessage(callback func(channel string, user User, message RawMessage)) {}
func OnNewUsernoticeMessage(callback func(channel string, user User, message Message)) {}
```

# Option 2: Specific Split

While this is heavily API breaking, the idea is that it only sends the information relevant to each message type, instead of it being hidden in `Tags`.

- `Tags` is still in `RawMessage` to support new message types.
- I combined Userstate and GlobalUserstate as the only difference was the `UserID` in GlobalUserstate.
- I didn't initially combine Notice and Usernotice because there is a bigger difference, but we could do.

```go
type RawMessage struct {
	Type    MessageType
	RawType string
	Raw     string
	Tags    map[string]string
}

type Message struct {
	RawMessage
	Time   time.Time
	ID     string
	RoomID string
	Emotes []*Emote
	Text   string
}

type RawUser struct {
	Name        string
	DisplayName string
	Color       string
	Badges      map[string]int
}

type User struct {
	RawUser
	ID string
}

// UNSERT

func OnNewUnsetMessage(callback func(channel string, user RawUser, message RawMessage)) {}

// CLEARCHAT

type ClearchatMessage struct {
	Message
	BanDuration int
}

func OnNewClearchatMessage(callback func(channel string, user User, message ClearchatMessage)) {}

// PRIVMSG

type ChatMessage struct {
	Bits int
}

func OnNewMessage(callback func(channel string, user User, message ChatMessage)) {}

func OnNewWhisper(callback func(user User, message Message)) {}

// ROOMSTATE

type RoomstateMessage struct {
	Message
	Language string
	Modes    map[string]bool
}

func OnNewRoomstateMessage(callback func(channel string, message RoomstateMessage)) {}

// NOTICE

type NoticeMessage struct {
	RawMessage
	NoticeType    string
	NoticeMessage string
	NoticeParams  map[string]string
}

func OnNewNoticeMessage(callback func(channel string, message NoticeMessage)) {}

// USERSTATE

type UserstateUser struct {
	User
	EmoteSets []string
}

func OnNewUserstateMessage(callback func(channel string, user UserstateUser, message RawMessage)) {}

// USERNOTICE

type UsernoticeMessage struct {
	Message
	NoticeType    string
	NoticeMessage string
	NoticeParams  map[string]string
}

func OnNewUsernoticeMessage(callback func(channel string, user User, message UsernoticeMessage)) {}
```

**Comment by gempir** [comment]
Alright personally. I like Option 2 a lot more. I think if we break API we should get it right. And it improves documentation of twitch features a lot by showing what type of message offers what kind of data. 

@pajlada Do you have any opinion here?

**Comment by pajlada** [comment]
I also agree that if we're going to make breaking changes, I much prefer Option 2. I'd like to really make sure the API is polished before making the change

**Comment by FletcherCodes** [comment]
Sweet! When you say "make sure the API is polished" are you talking about the proposed changes, or in relation to the pull request you're working on?

If you're talking about the changes, I can get a pull request up this week. It may differ slightly to what I proposed above to ensure no/minimal breaking changes when adding new message types, but it'll follow the same path of showing what data each type offers.

**Comment by pajlada** [comment]
@FletcherCodes nah, nothing related to the PR I'm working on. I mean I want all the structs, names of the members etc to be really thought through, together, to make sure that we're naming everything properly since we're going to do a breaking change.

When you get a pull request up, we can start discussing naming and go from there to try to make the API as good as possible

**Comment by jrbury** [comment]
I also like Option 2, a good place to see where this style is used is (https://github.com/bwmarrin/discordgo) which is very nice to use, the only real downside is that it does require a bit more work in ensuring our definition of the data types stay in sync with those of Twitch.

**Comment by FletcherCodes** [comment]
Am pretty much finished. Just doing some tests now, and will give it a final once over tomorrow morning before opening a pull request. 👍

**Comment by gempir** [comment]
@jrbury  I really like that style, I think we should also implement it at some point.

**Comment by pajlada** [comment]
After @FletcherCodes's awesome work in #78 , we've merged it into the dev branch https://github.com/gempir/go-twitch-irc/tree/dev
While this is being tested out, a few other API changes/additions are being discussed
Namely the discordgo style of https://godoc.org/github.com/bwmarrin/discordgo#Session.AddHandler
