### ISSUE TITLE
Capturing IRC error "Login authentication failed"

### ISSUE THREAD

**Issue by pajlada** [gempir/go-twitch-irc#55]
Thoughts on capturing the "Login authentication failed" error and returning and error from Connect() if we jump into that error? Would make it a bit more obvious if we accidentally use the wrong oauth token

@gempir 
I have an implementation that I use locally atm but I would like to know if it fits the library before I bother to clean up the code and PR

Example usage code (note that nothing changed, we just propagate the error to `Connect`):
```go
package main

import (
	twitch "github.com/gempir/go-twitch-irc"
)

func main() {
	client := twitch.NewClient("adaljap", "penis")

	client.OnNewMessage(func(channel string, user twitch.User, message twitch.Message) {
	})

	client.Join("pajlada")

	err := client.Connect()
	if err != nil {
		panic(err)
	}
}
```

Console output:
```sh
$ go run main.go
panic: login authentication failed

goroutine 1 [running]:
main.main()
        C:/dev/go/src/github.com/pajlada/twitchtags/main.go:17 +0x25e
exit status 2
```

**Comment by gempir** [comment]
I agree. This should be normal behavior

**Comment by pajlada** [comment]
👍 I'll work on the PR then
