### ISSUE TITLE
Cannot get basic "Getting Started" example to work

### ISSUE THREAD

**Issue by GaussianZero** [gempir/go-twitch-irc#57]
Is this library still functional (I know twitch has modified their APIs somewhat recently). I've tried the hello world app at https://github.com/gempir/go-twitch-irc#getting-started however, no messages are being printed for me (will continue to debug, but no errors, and no functionality, so wondering whether others have issues.

**Comment by gempir** [comment]
Any reference to the API changes? I haven't tried the example yet, since I'm on mobile but my production app is running fine with it.

**Comment by GaussianZero** [comment]
regarding the API changes, can't find a twitch reference, but i know endpoints shuffled around (e.g. new endpoint for refresh token is https://id.twitch.tv/oauth2/token, whereas it used to be like "https://api.twitch.tv/kraken/oauth2/token")

If you've got it confirmed working, it must be on my end. I just wanted to check that this libary's still maintained and up to date with the latest. 

Any suggestions on how to debug? I have copied the example exactly (only modifying the bot username and auth token, and the channel to join). Perhaps my access token doesn't have the right scopes? (IIRC it has whispers:{read,edit} and chat:{read,edit} ). Otherwise I'll just start to pick it apart to find my bug.

**Comment by gempir** [comment]
I have only tried anonymous authentication, I will try user authentication when I'm back home today.

API changes usally don't matter to this API, since it doesn't do any authentication for you (like getting tokens etc.) 

Usally i test my login stuff with Tokens from here: http://twitchapps.com/tmi/

**Comment by gempir** [comment]
I just tried authentication, works fine. This library is fine, so must be something with your code.

**Comment by GaussianZero** [comment]
confirmed that something is bad with one of our machines (fresh machine runs just fine). likely some leftovers from an earlier fork of the codebase, though i did try to rm the local changes and re-pull, my hunch is that it didn't get us to an install that was as fresh and clean as i thought.

Thanks for your help and quick response, sorry for the noise!
