### ISSUE TITLE
Connection stability and health checks

### ISSUE THREAD

**Issue by gempir** [gempir/go-twitch-irc#58]
To ensure we still are connected to TMI we should send pings ourselves and expect a response from tmi.

If a connection is inactive for more than 15s we should send a ping and check the response.
SetReadTimeout/SetWriteTimeout could both be useful here although not required. 

Also currently we don't handle the joins of the user at all. We should be rejoining the user if the connection died. **Edit: We already do handle rejoining channels.**

**Comment by pajlada** [comment]
>Also currently we don't handle the joins of the user at all. We should be rejoining the user if the connection died.

What do you mean by this? If you mean channels that the library user has joined, then we handle that here: https://github.com/gempir/go-twitch-irc/blob/master/client.go#L281
