### ISSUE TITLE
Gain/lose moderator status

### ISSUE THREAD

**Issue by moneyzmey** [gempir/go-twitch-irc#60]
Is it possible to gain or lose moderator status ?

**Comment by gempir** [comment]
Sending `.mod name` or respectively unmod should work

**Comment by moneyzmey** [comment]
Few questions:
1. Should I use command Say ?
2. Should I be login by channel owner ?

**Comment by gempir** [comment]
Either channel owner or for unmod also being the mod you want to unmod works. And yes use say

**Comment by moneyzmey** [comment]
Your solution work 100%! Thanks a lot
