### ISSUE TITLE
Providing empty credentials results in Connect() hanging indefinitely.

### ISSUE THREAD

**Issue by volgorean** [gempir/go-twitch-irc#63]
```go
client = twitch.NewClient("", "")
err := client.Connect()
if err != nil {
  log.Println(err)
}
log.Println("I wont happen.")
```

I have a fix in https://github.com/volgorean/go-twitch-irc/commit/bea645c576d35da1d6b8880077cc4f282d91324e but I'm not sure its a good one as I'm not sure if there are other cases that would result in an io.EOF error that should not be Fatal. I also noticed that [the tests](https://github.com/gempir/go-twitch-irc/blob/master/client_test.go#L52) explicitly ignore io.EOF errors.

An alternative solution would be to check that the provided credentials are not empty but this seems suboptimal since this library supports connecting to a custom irc server (which may allow you to connect without credentials.)

**Comment by volgorean** [comment]
This may be what https://github.com/gempir/go-twitch-irc/issues/46 was talking about.

**Comment by gempir** [comment]
EOF can't be fatal it needs to allow a reconnect.

I'm not 100% sure anymore why the tests explicitly ignore EOF errors but might have been stability thing. 

I'm still unsure whats the best way to handle this. I'm wondering if we should count the attempted new connections and break after X amount of times in a Y time frame.

**Comment by pajlada** [comment]
@volgorean Please give this another try and let me know if it's still an issue!

**Comment by volgorean** [comment]
@pajlada Just tried it out and it seems to return an "login authentication failed" error properly now when empty credentials are provided. Thanks :)
