### ISSUE TITLE
Concurrent map read and write

### ISSUE THREAD

**Issue by GaussianZero** [gempir/go-twitch-irc#66]
There is a concurrent read/write on the read ofmap c.channelUserlist[channel] (client.go ~line 391) With heavy usage, and departs, in can conflict with the write (delete) at 181.

I fixed this locally by using the same mutex c.channelsMtx (hope that fixes it!)

**Comment by gempir** [comment]
Hey thanks for the tip. Would you mind creating a PR for that?

**Comment by GaussianZero** [comment]
Sure - i may let it soak for a bit first, i get the error on the order of once in 12-24 hours, but if that seems to do the trick, will send a PR

**Comment by gempir** [comment]
I can't reproduce this anymore. We use the mutex there currently.
