### ISSUE TITLE
Emoji slice out of bounds

### ISSUE THREAD

**Issue by GaussianZero** [gempir/go-twitch-irc#67]
The read of runes[start : end+1] ~line 249 of message.go can yield an out of bounds error. I haven't been able to pinpoint what the string looks like, but for now I just added a if start < 0 || end+1 >= len(runes) { continue } block.

**Comment by gempir** [comment]
interesting. Haven't had that yet. The message that caused that would be super useful.

**Comment by GaussianZero** [comment]
updated the code to a block with a print and a continue, so hoping to have a message here in the next few days. will update accordingly.

**Comment by GaussianZero** [comment]
For what it's worth, I got two messages in Russian, however when re-sending them the library did not exhibit the error again. So it seems it's not just a function of the text in the message. Perhaps there is some state that's getting corrupted when there are many connections.

**Comment by gempir** [comment]
What do you mean with many connections? go-twitch-irc currently only supports a single connection.

**Comment by GaussianZero** [comment]
I mean that it's connected to and listening to many channels. if that's not supported, feel free to close this out.

**Comment by gempir** [comment]
No. That's obviously supported. But I mean that there is only 1 single TCP connection to TMI.

**Comment by FletcherCodes** [comment]
After around 540k messages, I believe I hit the same issue. I've added a deferred recover function to `ParseMessage` that prints the last line received, the error, and the stack trace. Will report back when I hit it again.
