### ISSUE TITLE
Rename server key and cert to "test_server"

### ISSUE THREAD

**Issue by VitorFalcao** [gempir/go-twitch-irc#9]
@gempir  I was looking at the repo now and realized this would be a good idea, just to make clear that it is only for testing. What do you think?

**Comment by gempir** [comment]
Probably should start with folders like test_resources

**Comment by VitorFalcao** [comment]
Good point! So only move them to a folder called "test_resources" or do both (move and rename)?

**Comment by gempir** [comment]
Just moving would be enough. IMO

**Comment by VitorFalcao** [comment]
I am on it.
