### ISSUE TITLE
Handle GLOBALUSERSTATE message

### ISSUE THREAD

**Issue by pajlada** [gempir/go-twitch-irc#98]
Example message: `@badge-info=;badges=;color=#2E8B57;display-name=pajbot;emote-sets=0,15961,24569,24570;user-id=82008718;user-type= :tmi.twitch.tv GLOBALUSERSTATE`

https://dev.twitch.tv/docs/irc/tags/#globaluserstate-twitch-tags

**Comment by gempir** [comment]
Done in #136
